name: Express Server Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  runs_server_tests:
    name: Run server runs_server_tests
    runs-on: ubuntu-latest

    steps:
        - name: Clone repo to Actions
          uses: actions/checkout@v3
        
        - name: Set up NodeJS on the Actions Computer
          uses: actions/setup-node@v3
          with:
            node-version: 18
      
        - name: Start MongoDB
          uses: supercharge/mongodb-github-action@1.10.0
          with:
            mongodb-version: latest
            mongodb-db: IGotYouBoo-test

        - name: Install server dependencies
          run: npm install

        - name: Seed and test db
          run: npm run ci-reseed-and-test
          env:
            CI: true